apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kl1tig0je-python 
  janus-idp.io/tekton: kl1tig0je-python
  backstage.io/kubernetes-id: kl1tig0je-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kl1tig0je-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  