apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kl1tig0je-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kl1tig0je-python 
  name: kl1tig0je-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kl1tig0je-python 
